// packages/react/src/form.ts
import { useMemo, useRef } from 'react'
import { createOAuthForm, type OAuthFieldError, type OAuthFormOptions, oauthFormView } from 'react-oauth-oidc/core'
import { useOAuthError, useStoreValue } from './hooks'
import { useOAuthInstance } from './provider'

export interface OAuthFormField {
  value: string
  error: OAuthFieldError
  /** gate error display on this: a pristine form should not shout about empty required fields */
  showError: boolean
  onChange: (value: string) => void
}

export interface OAuthForm {
  username: OAuthFormField
  password: OAuthFormField
  valid: boolean
  submitted: boolean
  submitting: boolean
  error: string | undefined
  dismissError: () => void
  passwordVisible: boolean
  togglePasswordVisible: () => void
  submit: (event?: { preventDefault?: () => void }) => Promise<void>
  reset: () => void
  maxLength: number
}

export type UseOAuthFormOptions = OAuthFormOptions

/**
 * The resource-owner password form. The rules — when a field may show an error, what survives a
 * rejected attempt, when a dismissed error comes back — are `@oidcraft/client`'s and are shared with
 * the Vue and Angular bindings; this is the React wrapper and nothing else.
 */
export const useOAuthForm = (options: UseOAuthFormOptions = {}): OAuthForm => {
  const oauth = useOAuthInstance()

  // Held in a ref because the options *seed* the form rather than bind to it: they are an object
  // literal at almost every call site, so depending on their identity would rebuild the controller
  // every render and throw away whatever the user had typed. This is what `useState(username)` did
  // before, said out loud.
  const seed = useRef(options)

  const controller = useMemo(
    () =>
      createOAuthForm(
        {
          login: parameters => oauth.login(parameters),
          isAuthorized: oauth.isAuthorized,
          errorDescription: oauth.errorDescription
        },
        seed.current
      ),
    [oauth]
  )

  const state = useStoreValue(controller.store, snapshot => snapshot)
  const flowError = useOAuthError()
  const view = oauthFormView(state, flowError, controller.maxLength)

  return {
    username: { ...view.username, onChange: controller.setUsername },
    password: { ...view.password, onChange: controller.setPassword },
    valid: view.valid,
    submitted: view.submitted,
    submitting: view.submitting,
    error: view.error,
    dismissError: controller.dismissError,
    passwordVisible: view.passwordVisible,
    togglePasswordVisible: controller.togglePasswordVisible,
    submit: controller.submit,
    reset: controller.reset,
    maxLength: controller.maxLength
  }
}

// packages/angular/src/form.ts
import { computed, inject, type Signal } from '@angular/core'
import { createOAuthForm, type OAuthFieldError, type OAuthFormOptions, oauthFormView } from '@oidcraft/client'
import { OAUTH } from './oauth'
import { storeSignal } from './signals'

export interface OAuthFormField {
  value: Signal<string>
  error: Signal<OAuthFieldError>
  /** gate the display on this: a pristine form should not shout about empty required fields */
  showError: Signal<boolean>
  set: (value: string) => void
}

export interface OAuthForm {
  username: OAuthFormField
  password: OAuthFormField
  valid: Signal<boolean>
  submitted: Signal<boolean>
  submitting: Signal<boolean>
  error: Signal<string | undefined>
  dismissError: () => void
  passwordVisible: Signal<boolean>
  togglePasswordVisible: () => void
  submit: (event?: { preventDefault?: () => void }) => Promise<void>
  reset: () => void
  maxLength: number
}

/**
 * The resource-owner password form as signals. The rules — when a field may show an error, what
 * survives a rejected attempt, when a dismissed error comes back — are `@oidcraft/client`'s and are
 * shared with the Vue and React bindings; this is the reactive wrapper and nothing else.
 *
 * Call it in an injection context. v8 shipped this as a Material component under
 * `ngx-oauth/component`; see the README for why that entry is gone.
 */
export const oauthForm = (options: OAuthFormOptions = {}): OAuthForm => {
  const oauth = inject(OAUTH)
  const controller = createOAuthForm(
    {
      login: parameters => oauth.login(parameters),
      isAuthorized: () => oauth.isAuthorized(),
      errorDescription: () => oauth.errorDescription()
    },
    options
  )

  const state = storeSignal(controller.store, controller.state)
  // the flow error is read here rather than inside the controller so this computed tracks it
  const view = computed(() => oauthFormView(state(), oauth.errorDescription(), controller.maxLength))

  const field = (name: 'username' | 'password'): OAuthFormField => ({
    value: computed(() => view()[name].value),
    error: computed(() => view()[name].error),
    showError: computed(() => view()[name].showError),
    set: name === 'username' ? controller.setUsername : controller.setPassword
  })

  return {
    username: field('username'),
    password: field('password'),
    valid: computed(() => view().valid),
    submitted: computed(() => view().submitted),
    submitting: computed(() => view().submitting),
    error: computed(() => view().error),
    dismissError: controller.dismissError,
    passwordVisible: computed(() => view().passwordVisible),
    togglePasswordVisible: controller.togglePasswordVisible,
    submit: controller.submit,
    reset: controller.reset,
    maxLength: controller.maxLength
  }
}
